"""Self-custodial EVM wallet generation with AES-256-GCM encryption.

Security model:
- The private key is generated in-memory, encrypted with WALLET_ENC_SECRET
  (a 32-byte server secret, normally from a KMS), and ONLY the ciphertext is
  persisted to the database.
- The plaintext private key and the BIP-39-style seed phrase are returned to
  the caller exactly ONCE (in the register response) and are NEVER logged,
  NEVER persisted in plaintext, and NEVER written to disk by this module.
- If WALLET_ENC_SECRET is unset, wallet generation is refused (fail-closed).
"""
from __future__ import annotations

import os
import json
import base64
import secrets
import logging

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from eth_account import Account

logger = logging.getLogger("a2z.wallet_gen")

# 12-word BIP-39 mnemonic is generated by eth_account from the key.
# We surface the mnemonic (seed phrase) to the user exactly once.


def _get_enc_secret() -> bytes | None:
    """Return the 32-byte WALLET_ENC_SECRET, or None if not configured."""
    raw = os.getenv("WALLET_ENC_SECRET")
    if not raw:
        logger.warning("WALLET_ENC_SECRET not set (len check skipped)")
        return None
    raw = raw.strip()
    logger.warning("WALLET_ENC_SECRET present, raw_len=%d", len(raw))
    try:
        # Accept raw 32-byte (64 hex chars) or any secret string (hashed to 32 bytes).
        if len(raw) == 64:
            return bytes.fromhex(raw)
        # Derive a stable 32-byte key from arbitrary secret text.
        import hashlib

        return hashlib.sha256(raw.encode("utf-8")).digest()
    except Exception:
        return None


def generate_wallet() -> dict:
    """Generate a fresh EVM wallet.

    Returns:
        {
            "address": "0x...",
            "private_key": "0x...",   # plaintext, shown ONCE
            "seed_phrase": "word1 ... word12",  # shown ONCE
            "encrypted_blob": "base64-nonce+ct",  # persisted only this
        }
    """
    from eth_account import Account
    from eth_account.hdaccount import generate_mnemonic

    # HD-wallet / mnemonic features are opt-in in eth_account.
    Account.enable_unaudited_hdwallet_features()

    secret = _get_enc_secret()
    if secret is None or len(secret) != 32:
        raise RuntimeError(
            "WALLET_ENC_SECRET not configured (need 32-byte secret). "
            "Wallet generation is disabled."
        )

    # Generate a fresh BIP-39 mnemonic, then derive the account from it so the
    # user can recover the wallet from the seed phrase alone.
    mnemonic_phrase = generate_mnemonic(12, lang="english")
    acct = Account.from_mnemonic(mnemonic_phrase)
    private_key = acct.key.hex()  # 0x-prefixed hex string
    address = acct.address
    seed_phrase = mnemonic_phrase  # 12-word BIP-39 seed phrase

    # Encrypt the private key (hex string) with AES-256-GCM.
    aes = AESGCM(secret)
    nonce = secrets.token_bytes(12)
    ct = aes.encrypt(nonce, private_key.encode("utf-8"), None)
    encrypted_blob = base64.b64encode(nonce + ct).decode("ascii")

    # Sanity: decrypt immediately to ensure round-trip works (in-memory only).
    try:
        pt = aes.decrypt(nonce, ct, None)
        assert pt.decode("utf-8") == private_key
    except Exception as exc:
        raise RuntimeError("Wallet encryption self-check failed") from exc

    # IMPORTANT: plaintext key/seed are returned to caller once and discarded
    # from this scope. They are never logged or persisted in plaintext.
    return {
        "address": address,
        "private_key": private_key,
        "seed_phrase": seed_phrase,
        "encrypted_blob": encrypted_blob,
    }


def decrypt_wallet(encrypted_blob: str) -> str:
    """Recover the plaintext private key from a stored encrypted_blob.

    Used server-side ONLY when executing on behalf of a custodial-but-generated
    wallet (e.g. demo). Caller must be authorized. Never log the result.
    """
    secret = _get_enc_secret()
    if secret is None or len(secret) != 32:
        raise RuntimeError("WALLET_ENC_SECRET not configured.")
    raw = base64.b64decode(encrypted_blob)
    nonce, ct = raw[:12], raw[12:]
    aes = AESGCM(secret)
    return aes.decrypt(nonce, ct, None).decode("utf-8")
